dev
Wizarrrr/wizarr pull request #202
Opened 2023-09-05 10:25 UTC by Ryphier

2023-09-05 14:20 UTC, realashleybailey requested changes
The placeholder attribute specifies a short hint that describes the expected value of an input field (e.g. a sample value). We have labels to specify input type, please undo these changes and resubmit.

2023-09-05 14:24 UTC, realashleybailey commented on app/templates/wizard/requests.html
This does not need changing.

2023-09-05 14:28 UTC, realashleybailey commented on app/templates/wizard/jellyfin/tips.html
You removed punctuation for the title, "Eh, So, What is Jellyfin exactly?" is fine.

We can not name Netflix specifically, please keep it generalised. 
Paragraph 1 can be "Jellyfin is an opensource platform that lets you stream movies and TV shows in one place.
        It's like having your own personal movie theater right at your fingertips! Think of it as a digital library of
        your favorite content that you can access from anywhere, on any device - your phone, tablet, laptop, smart TV,
        you name it.""

Paragraph 2 is fine
Link is fine too

2023-09-05 14:29 UTC, realashleybailey commented on app/templates/wizard/jellyfin/download.html
Remove "(it works great!) or another device"

2023-09-05 14:30 UTC, realashleybailey commented on app/templates/wizard/jellyfin/tips.html
Why on earth do we need a bloody orangutan 😂

2023-09-06 00:40 UTC, Ryphier commented
Hahaha shit! I Didn't mean to pull this!

2023-09-06 00:40 UTC, closed without merging