Live TV Access for Jellyfin/Emby invites
wizarrrr/wizarr pull request #382
Opened 2024-04-22 18:47 UTC by JamsRepos

2024-04-22 20:01 UTC, MrDynamo requested changes

2024-04-22 20:01 UTC, mrdynamo commented on apps/wizarr-backend/wizarr_backend/helpers/jellyfin.py
Logic statement needs to be reversed

2024-04-22 20:48 UTC, MrDynamo approved these changes
LGTM!

2024-04-22 20:52 UTC, merged

2024-04-30 16:24 UTC, JamsRepos commented on apps/wizarr-backend/wizarr_backend/app/migrator/migrations/2024-04-22_19-17-37.py
> +#
This whole file needs its dates amended, it's the 30th and it's been made as the 22nd.